- hosts: servers
  become: true
  gather_facts: true
  vars:
    ansible_user: "{{ adempiere_username }}"
    ansible_password: "{{ adempiere_user_password }}"
    ansible_become_password: "{{ adempiere_user_become_pass }}"
    ansible_port: "{{ custom_sshport }}"
  roles:
    - install-docker
